---
- name: Oracle proxy config and apt-get update
  copy: src=../files/oracle_proxy.conf dest=/etc/apt/apt.conf owner=root group=root mode=0644
  #Allowing the user to skip proxy setup or not depending on location of deployment.
  tags: 
   - proxy

- shell: "apt-get update && apt-get install -y apt-transport-https curl"

- name: Adding repo
  apt_repository:
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present

- name: "Upading apt-get"
  shell: "apt-get update"
  
- name: install docker and kubernetes
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - ntp

#Running post configurations and activating some kernel modules
- name: Running post configurations
  command: modprobe {{ item }}
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

#Restarting services and modifying the modules file
- lineinfile: path=/etc/modules line='{{ item }}' create=yes state=present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4
  - sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes sysctl_set=yes
  - service: name=docker state=restarted enabled=yes
  - service: name=ntp state=restarted enabled=yes
  - service: name=kubelet state=restarted enabled=yes